import type { MikeWorkflow, ColumnConfig } from "../shared/types";

export interface WorkflowTranslations {
    t: (key: string) => string;
    prompts: Record<string, string>;
}

function col(
    index: number,
    t: (key: string) => string,
    base: string,
    extra?: Partial<Omit<ColumnConfig, "index" | "name" | "prompt">>
): ColumnConfig {
    return {
        index,
        name: t(`${base}.name`),
        prompt: t(`${base}.prompt`),
        ...extra,
    };
}

export function getBuiltinWorkflows(
    t: (key: string) => string,
    prompts: Record<string, string>
): MikeWorkflow[] {
    return [
        {
            id: "builtin-cp-checklist",
            user_id: null,
            is_system: true,
            created_at: "",
            title: t("builtin-cp-checklist.title"),
            type: "assistant",
            practice: t("builtin-cp-checklist.practice"),
            prompt_md: prompts["builtin-cp-checklist"] ?? null,
            columns_config: null,
        },
        {
            id: "builtin-coc-dd",
            user_id: null,
            is_system: true,
            created_at: "",
            title: t("builtin-coc-dd.title"),
            type: "tabular",
            practice: t("builtin-coc-dd.practice"),
            prompt_md: prompts["builtin-coc-dd"] ?? null,
            columns_config: [
                col(0, t, "builtin-coc-dd.columns.parties", { format: "bulleted_list" }),
                col(1, t, "builtin-coc-dd.columns.date", { format: "date" }),
                col(2, t, "builtin-coc-dd.columns.term", { format: "text" }),
                col(3, t, "builtin-coc-dd.columns.change_of_control_clause"),
                col(4, t, "builtin-coc-dd.columns.consent_required"),
                col(5, t, "builtin-coc-dd.columns.termination_rights"),
                col(6, t, "builtin-coc-dd.columns.put_call_options"),
                col(7, t, "builtin-coc-dd.columns.financial_implications"),
            ],
        },
        {
            id: "builtin-credit-summary",
            user_id: null,
            is_system: true,
            created_at: "",
            title: t("builtin-credit-summary.title"),
            type: "assistant",
            practice: t("builtin-credit-summary.practice"),
            prompt_md: prompts["builtin-credit-summary"] ?? null,
            columns_config: null,
        },
        {
            id: "builtin-commercial-agreement",
            user_id: null,
            is_system: true,
            created_at: "",
            title: t("builtin-commercial-agreement.title"),
            type: "tabular",
            practice: t("builtin-commercial-agreement.practice"),
            prompt_md: null,
            columns_config: [
                col(0, t, "builtin-commercial-agreement.columns.parties", { format: "bulleted_list" }),
                col(1, t, "builtin-commercial-agreement.columns.scope_of_work", { format: "text" }),
                col(2, t, "builtin-commercial-agreement.columns.amends_earlier_agreement", { format: "yes_no" }),
                col(3, t, "builtin-commercial-agreement.columns.effective_date", { format: "date" }),
                col(4, t, "builtin-commercial-agreement.columns.term", { format: "text" }),
                col(5, t, "builtin-commercial-agreement.columns.renewal", { format: "text" }),
                col(6, t, "builtin-commercial-agreement.columns.pricing", { format: "text" }),
                col(7, t, "builtin-commercial-agreement.columns.price_adjustments", { format: "text" }),
                col(8, t, "builtin-commercial-agreement.columns.penalties_for_late_payment", { format: "text" }),
                col(9, t, "builtin-commercial-agreement.columns.estimated_contract_value", { format: "monetary_amount" }),
                col(10, t, "builtin-commercial-agreement.columns.limitation_of_liability", { format: "text" }),
                col(11, t, "builtin-commercial-agreement.columns.ip_ownership", { format: "text" }),
                col(12, t, "builtin-commercial-agreement.columns.change_of_control", { format: "text" }),
                col(13, t, "builtin-commercial-agreement.columns.force_majeure", { format: "text" }),
                col(14, t, "builtin-commercial-agreement.columns.termination_rights", { format: "text" }),
                col(15, t, "builtin-commercial-agreement.columns.liquidated_damages", { format: "text" }),
                col(16, t, "builtin-commercial-agreement.columns.governing_law", { format: "text" }),
                col(17, t, "builtin-commercial-agreement.columns.dispute_resolution", { format: "text" }),
            ],
        },
        {
            id: "builtin-credit-agreement",
            user_id: null,
            is_system: true,
            created_at: "",
            title: t("builtin-credit-agreement.title"),
            type: "tabular",
            practice: t("builtin-credit-agreement.practice"),
            prompt_md: null,
            columns_config: [
                col(0, t, "builtin-credit-agreement.columns.lenders", { format: "bulleted_list" }),
                col(1, t, "builtin-credit-agreement.columns.borrowers", { format: "bulleted_list" }),
                col(2, t, "builtin-credit-agreement.columns.guarantors", { format: "bulleted_list" }),
                col(3, t, "builtin-credit-agreement.columns.other_parties", { format: "bulleted_list" }),
                col(4, t, "builtin-credit-agreement.columns.date_of_agreement", { format: "date" }),
                col(5, t, "builtin-credit-agreement.columns.facility", { format: "bulleted_list" }),
                col(6, t, "builtin-credit-agreement.columns.amount", { format: "monetary_amount" }),
                col(7, t, "builtin-credit-agreement.columns.purpose", { format: "text" }),
                col(8, t, "builtin-credit-agreement.columns.interest", { format: "text" }),
                col(9, t, "builtin-credit-agreement.columns.commitment_fee", { format: "text" }),
                col(10, t, "builtin-credit-agreement.columns.repayment_schedule", { format: "text" }),
                col(11, t, "builtin-credit-agreement.columns.maturity", { format: "date" }),
                col(12, t, "builtin-credit-agreement.columns.security", { format: "bulleted_list" }),
                col(13, t, "builtin-credit-agreement.columns.guarantees", { format: "bulleted_list" }),
                col(14, t, "builtin-credit-agreement.columns.financial_covenants", { format: "bulleted_list" }),
                col(15, t, "builtin-credit-agreement.columns.events_of_default", { format: "bulleted_list" }),
                col(16, t, "builtin-credit-agreement.columns.assignment", { format: "text" }),
                col(17, t, "builtin-credit-agreement.columns.change_of_control", { format: "text" }),
                col(18, t, "builtin-credit-agreement.columns.prepayment_fee", { format: "text" }),
                col(19, t, "builtin-credit-agreement.columns.governing_law", { format: "text" }),
                col(20, t, "builtin-credit-agreement.columns.dispute_resolution", { format: "text" }),
            ],
        },
        {
            id: "builtin-ediscovery",
            user_id: null,
            is_system: true,
            created_at: "",
            title: t("builtin-ediscovery.title"),
            type: "tabular",
            practice: t("builtin-ediscovery.practice"),
            prompt_md: null,
            columns_config: [
                col(0, t, "builtin-ediscovery.columns.date", { format: "date" }),
                col(1, t, "builtin-ediscovery.columns.type_of_document", { format: "text" }),
                col(2, t, "builtin-ediscovery.columns.sender", { format: "text" }),
                col(3, t, "builtin-ediscovery.columns.recipients", { format: "bulleted_list" }),
                col(4, t, "builtin-ediscovery.columns.summary", { format: "text" }),
                col(5, t, "builtin-ediscovery.columns.persons_mentioned", { format: "bulleted_list" }),
                col(6, t, "builtin-ediscovery.columns.privileged", { format: "yes_no" }),
            ],
        },
        {
            id: "builtin-supply-agreement",
            user_id: null,
            is_system: true,
            created_at: "",
            title: t("builtin-supply-agreement.title"),
            type: "tabular",
            practice: t("builtin-supply-agreement.practice"),
            prompt_md: null,
            columns_config: [
                col(0, t, "builtin-supply-agreement.columns.parties", { format: "bulleted_list" }),
                col(1, t, "builtin-supply-agreement.columns.effective_date", { format: "date" }),
                col(2, t, "builtin-supply-agreement.columns.products", { format: "bulleted_list" }),
                col(3, t, "builtin-supply-agreement.columns.term", { format: "text" }),
                col(4, t, "builtin-supply-agreement.columns.renewal", { format: "text" }),
                col(5, t, "builtin-supply-agreement.columns.delivery", { format: "text" }),
                col(6, t, "builtin-supply-agreement.columns.quality", { format: "text" }),
                col(7, t, "builtin-supply-agreement.columns.warranties", { format: "text" }),
                col(8, t, "builtin-supply-agreement.columns.liquidated_damages", { format: "text" }),
                col(9, t, "builtin-supply-agreement.columns.limitation_of_liability", { format: "text" }),
                col(10, t, "builtin-supply-agreement.columns.force_majeure", { format: "text" }),
                col(11, t, "builtin-supply-agreement.columns.termination_rights", { format: "text" }),
                col(12, t, "builtin-supply-agreement.columns.governing_law", { format: "text" }),
                col(13, t, "builtin-supply-agreement.columns.dispute_resolution", { format: "text" }),
            ],
        },
        {
            id: "builtin-spa",
            user_id: null,
            is_system: true,
            created_at: "",
            title: t("builtin-spa.title"),
            type: "tabular",
            practice: t("builtin-spa.practice"),
            prompt_md: null,
            columns_config: [
                col(0, t, "builtin-spa.columns.parties", { format: "bulleted_list" }),
                col(1, t, "builtin-spa.columns.date", { format: "date" }),
                col(2, t, "builtin-spa.columns.transaction", { format: "text" }),
                col(3, t, "builtin-spa.columns.consideration", { format: "monetary_amount" }),
                col(4, t, "builtin-spa.columns.key_conditions_precedent", { format: "bulleted_list" }),
                col(5, t, "builtin-spa.columns.completion_date", { format: "text" }),
                col(6, t, "builtin-spa.columns.warranties", { format: "text" }),
                col(7, t, "builtin-spa.columns.indemnities", { format: "text" }),
                col(8, t, "builtin-spa.columns.limitation_of_liability", { format: "text" }),
                col(9, t, "builtin-spa.columns.covenants", { format: "text" }),
                col(10, t, "builtin-spa.columns.exclusivity", { format: "text" }),
                col(11, t, "builtin-spa.columns.governing_law_jurisdiction", { format: "text" }),
                col(12, t, "builtin-spa.columns.dispute_resolution", { format: "text" }),
            ],
        },
        {
            id: "builtin-nda",
            user_id: null,
            is_system: true,
            created_at: "",
            title: t("builtin-nda.title"),
            type: "tabular",
            practice: t("builtin-nda.practice"),
            prompt_md: null,
            columns_config: [
                col(0, t, "builtin-nda.columns.direction", { format: "tag", tags: ["Mutual", "Unilateral"] }),
                col(1, t, "builtin-nda.columns.definition_of_confidential_information", { format: "text" }),
                col(2, t, "builtin-nda.columns.obligations_of_receiving_party", { format: "bulleted_list" }),
                col(3, t, "builtin-nda.columns.standard_carveouts_present", { format: "yes_no" }),
                col(4, t, "builtin-nda.columns.permitted_disclosures", { format: "bulleted_list" }),
                col(5, t, "builtin-nda.columns.term_and_duration", { format: "text" }),
                col(6, t, "builtin-nda.columns.return_and_destruction", { format: "text" }),
                col(7, t, "builtin-nda.columns.remedies", { format: "text" }),
                col(8, t, "builtin-nda.columns.governing_law_jurisdiction", { format: "text" }),
            ],
        },
        {
            id: "builtin-commercial-lease",
            user_id: null,
            is_system: true,
            created_at: "",
            title: t("builtin-commercial-lease.title"),
            type: "tabular",
            practice: t("builtin-commercial-lease.practice"),
            prompt_md: null,
            columns_config: [
                col(0, t, "builtin-commercial-lease.columns.landlord", { format: "text" }),
                col(1, t, "builtin-commercial-lease.columns.tenant", { format: "text" }),
                col(2, t, "builtin-commercial-lease.columns.guarantor", { format: "text" }),
                col(3, t, "builtin-commercial-lease.columns.premises", { format: "text" }),
                col(4, t, "builtin-commercial-lease.columns.date_of_lease", { format: "date" }),
                col(5, t, "builtin-commercial-lease.columns.term", { format: "text" }),
                col(6, t, "builtin-commercial-lease.columns.rent", { format: "monetary_amount" }),
                col(7, t, "builtin-commercial-lease.columns.rent_review", { format: "text" }),
                col(8, t, "builtin-commercial-lease.columns.service_charge", { format: "text" }),
                col(9, t, "builtin-commercial-lease.columns.insurance", { format: "text" }),
                col(10, t, "builtin-commercial-lease.columns.permitted_use", { format: "text" }),
                col(11, t, "builtin-commercial-lease.columns.repair_maintenance", { format: "text" }),
                col(12, t, "builtin-commercial-lease.columns.alterations", { format: "text" }),
                col(13, t, "builtin-commercial-lease.columns.assignment_subletting", { format: "text" }),
                col(14, t, "builtin-commercial-lease.columns.break_rights", { format: "text" }),
                col(15, t, "builtin-commercial-lease.columns.security_of_tenure", { format: "yes_no" }),
                col(16, t, "builtin-commercial-lease.columns.dilapidations", { format: "text" }),
                col(17, t, "builtin-commercial-lease.columns.rent_deposit", { format: "monetary_amount" }),
                col(18, t, "builtin-commercial-lease.columns.forfeiture_termination", { format: "text" }),
                col(19, t, "builtin-commercial-lease.columns.governing_law", { format: "text" }),
            ],
        },
        {
            id: "builtin-lpa",
            user_id: null,
            is_system: true,
            created_at: "",
            title: t("builtin-lpa.title"),
            type: "tabular",
            practice: t("builtin-lpa.practice"),
            prompt_md: null,
            columns_config: [
                col(0, t, "builtin-lpa.columns.general_partner", { format: "text" }),
                col(1, t, "builtin-lpa.columns.fund_name_jurisdiction", { format: "text" }),
                col(2, t, "builtin-lpa.columns.total_committed_capital", { format: "monetary_amount" }),
                col(3, t, "builtin-lpa.columns.capital_calls", { format: "text" }),
                col(4, t, "builtin-lpa.columns.penalties_for_failure_to_fund", { format: "text" }),
                col(5, t, "builtin-lpa.columns.investment_scope", { format: "text" }),
                col(6, t, "builtin-lpa.columns.fund_term", { format: "text" }),
                col(7, t, "builtin-lpa.columns.management_fee", { format: "text" }),
                col(8, t, "builtin-lpa.columns.carried_interest", { format: "text" }),
                col(9, t, "builtin-lpa.columns.preferred_return", { format: "percentage" }),
                col(10, t, "builtin-lpa.columns.gp_catch_up", { format: "text" }),
                col(11, t, "builtin-lpa.columns.clawback", { format: "text" }),
                col(12, t, "builtin-lpa.columns.fees_expenses", { format: "bulleted_list" }),
                col(13, t, "builtin-lpa.columns.distributions", { format: "text" }),
                col(14, t, "builtin-lpa.columns.key_person_clause", { format: "text" }),
                col(15, t, "builtin-lpa.columns.removal_of_gp", { format: "text" }),
                col(16, t, "builtin-lpa.columns.advisory_committee", { format: "text" }),
                col(17, t, "builtin-lpa.columns.transfer_restrictions", { format: "text" }),
                col(18, t, "builtin-lpa.columns.conflicts_of_interest", { format: "text" }),
                col(19, t, "builtin-lpa.columns.governing_law", { format: "text" }),
            ],
        },
        {
            id: "builtin-sha-summary",
            user_id: null,
            is_system: true,
            created_at: "",
            title: t("builtin-sha-summary.title"),
            type: "assistant",
            practice: t("builtin-sha-summary.practice"),
            prompt_md: prompts["builtin-sha-summary"] ?? null,
            columns_config: null,
        },
        {
            id: "builtin-shareholder-agreement",
            user_id: null,
            is_system: true,
            created_at: "",
            title: t("builtin-shareholder-agreement.title"),
            type: "tabular",
            practice: t("builtin-shareholder-agreement.practice"),
            prompt_md: null,
            columns_config: [
                col(0, t, "builtin-shareholder-agreement.columns.parties", { format: "bulleted_list" }),
                col(1, t, "builtin-shareholder-agreement.columns.date", { format: "date" }),
                col(2, t, "builtin-shareholder-agreement.columns.share_capital_classes", { format: "bulleted_list" }),
                col(3, t, "builtin-shareholder-agreement.columns.shareholdings", { format: "bulleted_list" }),
                col(4, t, "builtin-shareholder-agreement.columns.board_composition", { format: "text" }),
                col(5, t, "builtin-shareholder-agreement.columns.reserved_matters", { format: "bulleted_list" }),
                col(6, t, "builtin-shareholder-agreement.columns.pre_emption_new_shares", { format: "text" }),
                col(7, t, "builtin-shareholder-agreement.columns.transfer_restrictions", { format: "text" }),
                col(8, t, "builtin-shareholder-agreement.columns.right_of_first_refusal", { format: "text" }),
                col(9, t, "builtin-shareholder-agreement.columns.drag_along_rights", { format: "text" }),
                col(10, t, "builtin-shareholder-agreement.columns.tag_along_rights", { format: "text" }),
                col(11, t, "builtin-shareholder-agreement.columns.anti_dilution", { format: "text" }),
                col(12, t, "builtin-shareholder-agreement.columns.dividend_policy", { format: "text" }),
                col(13, t, "builtin-shareholder-agreement.columns.exit_liquidity", { format: "text" }),
                col(14, t, "builtin-shareholder-agreement.columns.deadlock", { format: "text" }),
                col(15, t, "builtin-shareholder-agreement.columns.non_compete", { format: "text" }),
                col(16, t, "builtin-shareholder-agreement.columns.confidentiality", { format: "text" }),
                col(17, t, "builtin-shareholder-agreement.columns.warranties", { format: "text" }),
                col(18, t, "builtin-shareholder-agreement.columns.governing_law", { format: "text" }),
                col(19, t, "builtin-shareholder-agreement.columns.dispute_resolution", { format: "text" }),
            ],
        },
        {
            id: "builtin-employment-agreement",
            user_id: null,
            is_system: true,
            created_at: "",
            title: t("builtin-employment-agreement.title"),
            type: "tabular",
            practice: t("builtin-employment-agreement.practice"),
            prompt_md: null,
            columns_config: [
                col(0, t, "builtin-employment-agreement.columns.employer", { format: "text" }),
                col(1, t, "builtin-employment-agreement.columns.employee", { format: "text" }),
                col(2, t, "builtin-employment-agreement.columns.date", { format: "date" }),
                col(3, t, "builtin-employment-agreement.columns.title", { format: "text" }),
                col(4, t, "builtin-employment-agreement.columns.compensation", { format: "text" }),
                col(5, t, "builtin-employment-agreement.columns.full_time_part_time", { format: "tag", tags: ["Full Time", "Part Time"] }),
                col(6, t, "builtin-employment-agreement.columns.independent_contractor", { format: "yes_no" }),
                col(7, t, "builtin-employment-agreement.columns.benefits", { format: "bulleted_list" }),
                col(8, t, "builtin-employment-agreement.columns.notice_employer_to_employee", { format: "text" }),
                col(9, t, "builtin-employment-agreement.columns.notice_employee_to_employer", { format: "text" }),
                col(10, t, "builtin-employment-agreement.columns.overtime", { format: "text" }),
                col(11, t, "builtin-employment-agreement.columns.working_hours", { format: "text" }),
                col(12, t, "builtin-employment-agreement.columns.variation", { format: "text" }),
                col(13, t, "builtin-employment-agreement.columns.ip_assignment", { format: "text" }),
                col(14, t, "builtin-employment-agreement.columns.grounds_for_termination", { format: "bulleted_list" }),
                col(15, t, "builtin-employment-agreement.columns.annual_leave", { format: "text" }),
            ],
        },
    ];
}

export const BUILTIN_WORKFLOW_IDS = new Set([
    "builtin-cp-checklist",
    "builtin-coc-dd",
    "builtin-credit-summary",
    "builtin-commercial-agreement",
    "builtin-credit-agreement",
    "builtin-ediscovery",
    "builtin-supply-agreement",
    "builtin-spa",
    "builtin-nda",
    "builtin-commercial-lease",
    "builtin-lpa",
    "builtin-sha-summary",
    "builtin-shareholder-agreement",
    "builtin-employment-agreement",
]);

export const BUILT_IN_IDS = BUILTIN_WORKFLOW_IDS;
