import React, { useEffect, useState } from "react";
import { useAuth } from "../contexts/AuthContext";
import { redeemPairingCode } from "../lib/auth";
import MikeLogo from "./MikeLogo";

// Local-password login / setup screen for the Word task pane.
//
// Wave 3 additions:
//   - "Pair with desktop" flow: user clicks the link, types a 6-digit code
//     generated by the desktop shell, add-in redeems it for a session token.
//   - Polls /auth/status every 3s while showing the login screen so the
//     copy can update as soon as the user finishes /auth/setup elsewhere.

export default function Login() {
  const { status, login, setup, refreshStatus } = useAuth();
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  const [showPair, setShowPair] = useState(false);
  const [pairCode, setPairCode] = useState("");
  const [pairBusy, setPairBusy] = useState(false);

  const isSetup = !!status && !status.initialized;

  // Background poll: while we're showing the login screen, check
  // /auth/status every 3 seconds. The desktop completing setup or the
  // user logging in elsewhere flips `initialized` / `authenticated`,
  // and the AuthProvider re-renders the tree.
  useEffect(() => {
    const id = setInterval(() => {
      refreshStatus().catch(() => {});
    }, 3000);
    return () => clearInterval(id);
  }, [refreshStatus]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");

    if (isSetup) {
      if (password.length < 6) {
        setError("Password must be at least 6 characters");
        return;
      }
      if (password !== confirmPassword) {
        setError("Passwords do not match");
        return;
      }
    }

    setLoading(true);
    try {
      if (isSetup) {
        await setup(password);
      } else {
        await login(password);
      }
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Something went wrong";
      setError(
        isSetup
          ? msg
          : msg.includes("401") || msg.toLowerCase().includes("invalid")
            ? "Incorrect password"
            : msg,
      );
    } finally {
      setLoading(false);
    }
  };

  const handleRedeem = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    if (!/^\d{6}$/.test(pairCode)) {
      setError("Pairing code must be 6 digits");
      return;
    }
    setPairBusy(true);
    try {
      await redeemPairingCode(pairCode);
      await refreshStatus();
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Pairing failed";
      setError(msg);
    } finally {
      setPairBusy(false);
    }
  };

  return (
    <div className="flex flex-col items-center justify-center min-h-screen px-4 bg-white">
      <div className="mb-6 text-center">
        <div className="inline-flex items-center justify-center w-14 h-14 mb-3 text-gray-900">
          <MikeLogo size={56} />
        </div>
        <h1 className="text-lg font-serif text-gray-900">
          {isSetup ? "Welcome to Mike" : "Mike AI"}
        </h1>
        <p className="text-xs text-gray-500 mt-0.5">
          {isSetup
            ? "Set a password to protect your local data."
            : showPair
              ? "Enter the 6-digit code from the Mike desktop app."
              : "Enter your password to continue."}
        </p>
      </div>

      {showPair ? (
        <form onSubmit={handleRedeem} className="w-full max-w-xs space-y-3">
          <div>
            <label className="block text-xs font-medium text-gray-700 mb-1">
              Pairing code
            </label>
            <input
              type="text"
              inputMode="numeric"
              maxLength={6}
              value={pairCode}
              onChange={(e) =>
                setPairCode(e.target.value.replace(/\D/g, "").slice(0, 6))
              }
              required
              autoFocus
              className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg outline-none focus:ring-2 focus:ring-mike-500 focus:border-transparent tracking-widest text-center"
              placeholder="000000"
            />
          </div>
          {error && (
            <p className="text-xs text-red-600 bg-red-50 border border-red-200 rounded-lg px-3 py-2">
              {error}
            </p>
          )}
          <button
            type="submit"
            disabled={pairBusy}
            className="w-full py-2 text-sm font-medium text-white bg-mike-500 rounded-lg hover:bg-mike-600 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          >
            {pairBusy ? "Pairing…" : "Pair"}
          </button>
          <button
            type="button"
            onClick={() => {
              setShowPair(false);
              setError("");
              setPairCode("");
            }}
            className="w-full py-1 text-xs text-gray-500 hover:text-gray-700"
          >
            Use password instead
          </button>
        </form>
      ) : (
        <form onSubmit={handleSubmit} className="w-full max-w-xs space-y-3">
          <div>
            <label className="block text-xs font-medium text-gray-700 mb-1">
              Password
            </label>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              autoFocus
              autoComplete={isSetup ? "new-password" : "current-password"}
              className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg outline-none focus:ring-2 focus:ring-mike-500 focus:border-transparent"
              placeholder="••••••••"
            />
          </div>

          {isSetup && (
            <div>
              <label className="block text-xs font-medium text-gray-700 mb-1">
                Confirm Password
              </label>
              <input
                type="password"
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
                required
                autoComplete="new-password"
                className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg outline-none focus:ring-2 focus:ring-mike-500 focus:border-transparent"
                placeholder="••••••••"
              />
            </div>
          )}

          {error && (
            <p className="text-xs text-red-600 bg-red-50 border border-red-200 rounded-lg px-3 py-2">
              {error}
            </p>
          )}

          <button
            type="submit"
            disabled={loading}
            className="w-full py-2 text-sm font-medium text-white bg-mike-500 rounded-lg hover:bg-mike-600 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          >
            {loading
              ? isSetup
                ? "Setting up…"
                : "Signing in…"
              : isSetup
                ? "Set Password"
                : "Sign In"}
          </button>

          {!isSetup && (
            <button
              type="button"
              onClick={() => {
                setShowPair(true);
                setError("");
              }}
              className="w-full py-1 text-xs text-mike-600 hover:text-mike-700"
            >
              I have a pairing code
            </button>
          )}
        </form>
      )}
    </div>
  );
}
