// Local-password auth helpers for the Word add-in. Mirrors the frontend's
// `mikeAuth.ts` — same backend endpoints, same localStorage-backed token
// (Office task panes get their own per-host storage, which is fine for a
// single-user local app).

const TOKEN_KEY = "mike.token";

// `process.env.API_BASE_URL` is replaced by webpack's DefinePlugin at build
// time (see webpack.config.js / dotenv-webpack). We declare the global here
// because the add-in's tsconfig doesn't pull in @types/node.
declare const process: { env: { API_BASE_URL?: string } };

// Wave 3: when the add-in is served by the Mike backend itself
// (https://127.0.0.1:3002/addin/...), it talks to the API on the same
// origin — same scheme, same port, no mixed-content issues, and no manual
// configuration. The env override is preserved as an escape hatch for
// local development against a separately-running backend.
function defaultApiBase(): string {
  if (typeof window !== "undefined" && window.location?.origin) {
    return window.location.origin;
  }
  return "http://localhost:3001";
}

export const API_BASE = process.env.API_BASE_URL?.trim() || defaultApiBase();

export function getMikeToken(): string | null {
  try {
    return window.localStorage.getItem(TOKEN_KEY);
  } catch {
    return null;
  }
}

export function setMikeToken(token: string): void {
  try {
    window.localStorage.setItem(TOKEN_KEY, token);
  } catch {
    /* ignore */
  }
}

export function clearMikeToken(): void {
  try {
    window.localStorage.removeItem(TOKEN_KEY);
  } catch {
    /* ignore */
  }
}

export function authHeader(): Record<string, string> {
  const t = getMikeToken();
  return t ? { Authorization: `Bearer ${t}` } : {};
}

export interface AuthStatus {
  initialized: boolean;
  authenticated: boolean;
}

export async function fetchAuthStatus(): Promise<AuthStatus> {
  const res = await fetch(`${API_BASE}/auth/status`, {
    cache: "no-store",
    credentials: "include",
    headers: { ...authHeader(), Accept: "application/json" },
  });
  if (!res.ok) throw new Error(`auth/status ${res.status}`);
  return (await res.json()) as AuthStatus;
}

export async function setupPassword(password: string): Promise<string> {
  const res = await fetch(`${API_BASE}/auth/setup`, {
    method: "POST",
    credentials: "include",
    headers: { "Content-Type": "application/json", Accept: "application/json" },
    body: JSON.stringify({ password }),
  });
  if (!res.ok) throw new Error((await res.text()) || `setup ${res.status}`);
  const data = (await res.json()) as { token: string };
  setMikeToken(data.token);
  return data.token;
}

export async function loginWithPassword(password: string): Promise<string> {
  const res = await fetch(`${API_BASE}/auth/login`, {
    method: "POST",
    credentials: "include",
    headers: { "Content-Type": "application/json", Accept: "application/json" },
    body: JSON.stringify({ password }),
  });
  if (!res.ok) throw new Error((await res.text()) || `login ${res.status}`);
  const data = (await res.json()) as { token: string };
  setMikeToken(data.token);
  return data.token;
}

/**
 * Redeem a 6-digit pairing code generated by the desktop shell. Returns
 * the session token the add-in should store. Throws on bad/expired codes.
 */
export async function redeemPairingCode(code: string): Promise<string> {
  const res = await fetch(`${API_BASE}/auth/pair/redeem`, {
    method: "POST",
    credentials: "include",
    headers: { "Content-Type": "application/json", Accept: "application/json" },
    body: JSON.stringify({ code }),
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(text || `pair/redeem ${res.status}`);
  }
  const data = (await res.json()) as { token: string };
  setMikeToken(data.token);
  return data.token;
}

export async function logout(): Promise<void> {
  try {
    await fetch(`${API_BASE}/auth/logout`, {
      method: "POST",
      credentials: "include",
      headers: authHeader(),
    });
  } catch {
    /* best-effort */
  }
  clearMikeToken();
}
